#!/bin/bash -


wait_for_device()
{
    local device=$1
    local timeout=$2
    local waited=0

    echo "host: waiting for $device"

    while(! ip link show | grep -q $device); do

        if [ $waited -lt $timeout ]; then
            sleep 1
            waited=$(($waited + 1))
        else
            echo "host: $device not found [!!]"
            return 1
        fi
    done

    echo "host: $device found"
    return 0
}

case "$1" in
    start)
         ip link add letce0 type bridge
         wait_for_device letce0 10
         ip link set letce0 up
         sleep 1
         ip addr add 10.99.1.200/24 dev letce0
         iptables -I INPUT -i letce0 -j ACCEPT
         iptables -I FORWARD -i letce0 -j ACCEPT
         ethtool --offload  letce0 rx off tx off
         echo 0 > /sys/devices/virtual/net/letce0/bridge/multicast_snooping
         
         ;;

    prep)
         ;;
        
    stop)
         ip link set letce0 down
         ip link del letce0
         iptables -D INPUT -i letce0 -j ACCEPT
         iptables -D FORWARD -i letce0 -j ACCEPT
         ip link del dev aveth.4.0 &> /dev/null
         ip link del dev aveth.2.0 &> /dev/null
         ip link del dev aveth.3.0 &> /dev/null
         ip link del dev aveth.1.0 &> /dev/null
         ;;
esac
